---
layout: post
---

remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


social-network-links:
  email: "jasmine.le369@gmail.com"

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  reddit: false

# How to display the link to your website in the footer
#url-pretty: ""

# Add the website title to the title of every page
#title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50


navbar-img: "/Recipes-And-Ratings/various/image.jpeg"
#footer-img: "/Recipes-And-Ratings/various/image.jpg"
#page-img: "/assets/img/bgimage.png"


page-col: "#FFFFFF"
text-col: "#141414"
link-col: "#0564eb"
hover-col: "#0085A1"
#navbar-col: "#EAEAEA"
navbar-text-col: "#141414"
navbar-border-col: "#d97f43"
footer-col: "##bf7e3d"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"